# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_examples.ipynb.

# %% auto 0
__all__ = []

# %% ../01_examples.ipynb 1
import json, re
from pathlib import Path
from PIL import Image
from tqdm.auto import tqdm

from nbdev import show_doc
from fastcore.all import test_eq

from .core import draw_card, load_taboo_words, add_taboo_words
