# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/Taboo',
                'doc_host': 'https://gpucce.github.io',
                'git_url': 'https://github.com/gpucce/Taboo.jl',
                'lib_path': 'Taboo'},
  'syms': {}}