# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/Taboo',
                'doc_host': 'https://gpucce.github.io',
                'git_url': 'https://github.com/gpucce/Taboo.jl',
                'lib_path': 'Taboo'},
  'syms': { 'Taboo.core': { 'Taboo.core._capitalize_all': ('core.html#_capitalize_all', 'Taboo/core.py'),
                            'Taboo.core._resize_font': ('core.html#_resize_font', 'Taboo/core.py'),
                            'Taboo.core.add_taboo_words': ('core.html#add_taboo_words', 'Taboo/core.py'),
                            'Taboo.core.draw_card': ('core.html#draw_card', 'Taboo/core.py'),
                            'Taboo.core.load_taboo_words': ('core.html#load_taboo_words', 'Taboo/core.py')}}}